title: My Wrangler Studios Portfolio
description: This is my portfolio showcasing my projects and skills.
baseurl: ""
url: "https://Jf1491523.github.io" # replace YOURUSERNAME with your GitHub username
theme: jekyll-theme-hacker # replace “merlot” with your chosen theme from the list
